server:
  port: 3344
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weiguangchao/microservice-config.git  