server:
  port: 80
  servlet:
    context-path: /consumer
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka,http://eureka3003.com:3003/eureka
feign:
  hystrix:
    enabled: true    