spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_01?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # 微服务的名称
  application:
    name: microservice-dept
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka
  # 该实例在eureka中的唯一标识
  instance:
    instance-id: microservice-dept8001
    prefer-ip-address: true
info:
  app.name: ririiy-microservice
  company.name: www.ririiy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$